<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-1DCFOTD" name="features.loginORMTest" tests="9" failures="1" timestamp="29 May 2019 08:23:25 GMT" time="46.363" errors="0">
  <testcase name="TC06_login" time="5.071" classname="features.loginORMTest"/>
  <testcase name="TC08_login" time="4.790" classname="features.loginORMTest"/>
  <testcase name="TC07_login" time="6.448" classname="features.loginORMTest"/>
  <testcase name="TC05_login" time="4.936" classname="features.loginORMTest"/>
  <testcase name="TC02_login" time="4.756" classname="features.loginORMTest"/>
  <testcase name="TC01_login" time="5.267" classname="features.loginORMTest"/>
  <testcase name="TC03_login" time="4.719" classname="features.loginORMTest"/>
  <testcase name="TC04_login" time="5.214" classname="features.loginORMTest">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/dashboard&quot;
     but: was &quot;http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/auth/validateCredentials&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/dashboard"
     but: was "http://127.0.0.1/orangehrm-4.0/symfony/web/index.php/auth/validateCredentials"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at pages.login.LoginPage.landingToDashboardPage(LoginPage.java:56)
at features.loginORMTest.TC04_login(loginORMTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- TC04_login -->
  <testcase name="TC04_login" time="5.162" classname="features.loginORMTest">
    <skipped/>
  </testcase> <!-- TC04_login -->
</testsuite> <!-- features.loginORMTest -->
